### PR TITLE
Clock binding work

### PR DESCRIPTION
**Pull request by Harit-m**
zeropadding,binding work added

### CODE REVIEW

**Review by admwx7 — CHANGES_REQUESTED** [review]
- you've got merge conflicts
- new logic needs comments so we can sustain it in the future
- you've introduced some breaking styling changes that need to be removed
- new functionality needs to be opt-in, not always-on
- associate your PR with an open ticket so we can have feature related discussions on it please

**Review by admwx7 — CHANGES_REQUESTED** [review]
Sorry for not clarifying the comments thing, while inline comments are appreciated for clarity on sections that are particularly confusing, what I meant here is the functions themselves need documented using jsdocs: http://usejsdoc.org/

It's the documentation standard that Polymer relies on for generating documentation for the elements on their public pages (webcomponents.org docs are generated from these)

**Comment by Harit-m** [comment]
Please do not consider this PR.
I intended to send this to a different repository.
Sorry for the confusion

**Comment by admwx7** [comment]
PR sent to wrong repo, closing.

**Pull request closed without merging**
